---
# tasks file for sbaerlocher.composer

- name: Stat bin
  become: true
  stat:
    path: "{{ composer_bin }}"
  register: composer_bin_stat_result
  tags:
    - packages

- block:

    - name: Download installer
      become: true
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp

    - name: Install
      become: true
      command: "php /tmp/installer --install-dir=\"{{ composer_bin|dirname }}\" --filename=\"{{ composer_bin|basename }}\""

    - name: Remove installer
      become: true
      file:
        path: /tmp/installer
        state: absent

  when: not composer_bin_stat_result.stat.exists
  tags:
    - packages
